#include "catalogindex.h"

#include <QFileInfo>
#include <QSqlError>
#include <QSqlQuery>
#include <QVariant>

namespace catalog {

namespace {

// Column order shared by every SELECT, so readRow() can stay a single function.
const char* const kColumns =
    "id, path, name, file_size, file_mtime, width, height, "
    "node_count, lib_version, channels, created_at, last_opened, last_saved, "
    "starred, missing_since";

// Escapes the LIKE metacharacters so a search for "50%" doesn't match
// everything. Paired with ESCAPE '\' in the query.
QString escapeLike(const QString& term)
{
    QString out = term;
    out.replace(QLatin1Char('\\'), QLatin1String("\\\\"));
    out.replace(QLatin1Char('%'), QLatin1String("\\%"));
    out.replace(QLatin1Char('_'), QLatin1String("\\_"));
    return out;
}

QVariant nullIfZero(qint64 value)
{
    return value == 0 ? QVariant() : QVariant(value);
}

} // namespace

CatalogIndex::CatalogIndex() = default;

CatalogIndex::~CatalogIndex()
{
    close();
}

bool CatalogIndex::open(const QString& path)
{
    close();

    // index.db holds no blobs and is read far more than written, so the
    // defaults are right; only thumbs.db needs page_size/auto_vacuum tuning.
    Database::Options options;
    options.walMode = true;
    options.foreignKeys = true;

    if (!db.open(path, options))
        return false;

    const bool fresh = db.scalar(
                           QStringLiteral("SELECT count(*) FROM sqlite_master WHERE type='table'"))
                       == 0;

    if (fresh) {
        if (!createSchema()) {
            close();
            return false;
        }
        currentVersion = SchemaVersion;
        return true;
    }

    currentVersion = readSchemaVersion();

    if (currentVersion > SchemaVersion) {
        // Written by a newer build. Migrating backwards is guesswork and this
        // file cannot be regenerated by rescanning, so reopen read-only and let
        // the launcher show what it can.
        qWarning("catalog: index schema v%d is newer than this build (v%d); opening read-only",
                 currentVersion, SchemaVersion);
        db.close();

        Database::Options ro = options;
        ro.readOnly = true;
        if (!db.open(path, ro))
            return false;

        readOnly = true;
        return true;
    }

    if (currentVersion < SchemaVersion && !migrate(currentVersion)) {
        close();
        return false;
    }

    return true;
}

void CatalogIndex::close()
{
    db.close();
    readOnly = false;
    currentVersion = 0;
}

bool CatalogIndex::createSchema()
{
    QStringList statements;

    statements << QStringLiteral(R"(
        CREATE TABLE texture (
          id            INTEGER PRIMARY KEY,
          path          TEXT NOT NULL UNIQUE,
          name          TEXT NOT NULL,
          file_size     INTEGER NOT NULL DEFAULT 0,
          file_mtime    INTEGER NOT NULL DEFAULT 0,
          width         INTEGER,
          height        INTEGER,
          node_count    INTEGER,
          lib_version   TEXT,
          channels      INTEGER NOT NULL DEFAULT 0,
          created_at    INTEGER NOT NULL,
          last_opened   INTEGER,
          last_saved    INTEGER,
          starred       INTEGER NOT NULL DEFAULT 0,
          missing_since INTEGER
        )
    )");

    statements << QStringLiteral(R"(
        CREATE TABLE tag (
          texture_id INTEGER NOT NULL REFERENCES texture(id) ON DELETE CASCADE,
          tag        TEXT NOT NULL,
          PRIMARY KEY (texture_id, tag)
        ) WITHOUT ROWID
    )");

    statements << QStringLiteral(
        "CREATE INDEX ix_recent ON texture(last_opened DESC) WHERE missing_since IS NULL");
    statements << QStringLiteral("CREATE INDEX ix_name ON texture(name)");

    statements << QStringLiteral("CREATE TABLE meta (k TEXT PRIMARY KEY, v TEXT)");
    statements << QStringLiteral("INSERT INTO meta (k, v) VALUES ('schema_version', '%1')")
                      .arg(SchemaVersion);

    return db.execBatch(statements);
}

int CatalogIndex::readSchemaVersion()
{
    QSqlQuery query = db.prepare(QStringLiteral("SELECT v FROM meta WHERE k = 'schema_version'"));
    if (!query.exec() || !query.next())
        return 0;

    return query.value(0).toInt();
}

bool CatalogIndex::writeSchemaVersion(int version)
{
    QSqlQuery query = db.prepare(QStringLiteral(
        "INSERT INTO meta (k, v) VALUES ('schema_version', ?) "
        "ON CONFLICT(k) DO UPDATE SET v = excluded.v"));
    query.addBindValue(QString::number(version));
    if (!query.exec()) {
        db.setError(query.lastError().text());
        return false;
    }
    currentVersion = version;
    return true;
}

bool CatalogIndex::migrate(int fromVersion)
{
    // No migrations yet — v1 is the first shipped schema. When one is needed,
    // add a step here per version, each inside its own transaction, and bump
    // SchemaVersion. Steps must be additive: this file is the only copy of the
    // user's history.
    Q_UNUSED(fromVersion);
    return writeSchemaVersion(SchemaVersion);
}

// --- write points ---------------------------------------------------------

bool CatalogIndex::recordOpened(TextureRecord& rec, qint64 whenMs)
{
    return upsert(rec, Stamp::Opened, whenMs);
}

bool CatalogIndex::recordSaved(TextureRecord& rec, qint64 whenMs)
{
    return upsert(rec, Stamp::Saved, whenMs);
}

bool CatalogIndex::upsert(TextureRecord& rec, Stamp stamp, qint64 whenMs)
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return false;
    }
    if (rec.path.isEmpty()) {
        db.setError(QStringLiteral("cannot record a texture with no path"));
        return false;
    }

    if (rec.name.isEmpty())
        rec.name = QFileInfo(rec.path).completeBaseName();

    if (stamp == Stamp::Opened)
        rec.lastOpened = whenMs;
    else
        rec.lastSaved = whenMs;

    // created_at is preserved on conflict; every other column reflects what we
    // just learned from the document. starred and missing_since are handled
    // separately: starring is a user action this call knows nothing about, and
    // touching a file necessarily means it isn't missing.
    QSqlQuery query = db.prepare(QStringLiteral(R"(
        INSERT INTO texture (path, name, file_size, file_mtime,
                             width, height, node_count, lib_version, channels,
                             created_at, last_opened, last_saved, starred, missing_since)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, NULL)
        ON CONFLICT(path) DO UPDATE SET
            name          = excluded.name,
            file_size     = excluded.file_size,
            file_mtime    = excluded.file_mtime,
            width         = excluded.width,
            height        = excluded.height,
            node_count    = excluded.node_count,
            lib_version   = excluded.lib_version,
            channels      = excluded.channels,
            last_opened   = max(coalesce(texture.last_opened, 0),
                                coalesce(excluded.last_opened, 0)),
            last_saved    = max(coalesce(texture.last_saved, 0),
                                coalesce(excluded.last_saved, 0)),
            missing_since = NULL
    )"));

    query.addBindValue(rec.path);
    query.addBindValue(rec.name);
    query.addBindValue(rec.fileSize);
    query.addBindValue(rec.fileMtime);
    query.addBindValue(rec.width);
    query.addBindValue(rec.height);
    query.addBindValue(rec.nodeCount);
    query.addBindValue(rec.libVersion.isEmpty() ? QVariant() : QVariant(rec.libVersion));
    query.addBindValue(rec.channels);
    query.addBindValue(rec.createdAt != 0 ? rec.createdAt : whenMs);
    query.addBindValue(nullIfZero(rec.lastOpened));
    query.addBindValue(nullIfZero(rec.lastSaved));

    if (!query.exec()) {
        db.setError(query.lastError().text());
        qWarning("catalog: upsert failed for %s: %s", qPrintable(rec.path),
                 qPrintable(db.lastError()));
        return false;
    }

    // max() above can leave the in-memory record behind the stored row, and the
    // id is unknown on the update path, so read back rather than guess.
    const TextureRecord stored = byPath(rec.path);
    if (!stored.isValid()) {
        db.setError(QStringLiteral("row vanished immediately after upsert"));
        return false;
    }
    rec = stored;
    return true;
}

bool CatalogIndex::setStarred(qint64 id, bool starred)
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return false;
    }

    QSqlQuery query = db.prepare(QStringLiteral("UPDATE texture SET starred = ? WHERE id = ?"));
    query.addBindValue(starred ? 1 : 0);
    query.addBindValue(id);
    if (!query.exec()) {
        db.setError(query.lastError().text());
        return false;
    }
    return query.numRowsAffected() > 0;
}

bool CatalogIndex::remove(qint64 id)
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return false;
    }

    QSqlQuery query = db.prepare(QStringLiteral("DELETE FROM texture WHERE id = ?"));
    query.addBindValue(id);
    if (!query.exec()) {
        db.setError(query.lastError().text());
        return false;
    }
    return query.numRowsAffected() > 0;
}

int CatalogIndex::removeAllMissing()
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return 0;
    }

    QSqlQuery query = db.prepare(
        QStringLiteral("DELETE FROM texture WHERE missing_since IS NOT NULL"));
    if (!query.exec()) {
        db.setError(query.lastError().text());
        return 0;
    }
    return query.numRowsAffected();
}

bool CatalogIndex::clearRecents()
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return false;
    }

    return db.exec(QStringLiteral("UPDATE texture SET last_opened = NULL"));
}

// --- reconciliation -------------------------------------------------------

QVector<TextureRecord> CatalogIndex::allRecords() const
{
    QVector<TextureRecord> records;

    QSqlQuery query = const_cast<Database&>(db).prepare(
        QStringLiteral("SELECT %1 FROM texture").arg(QLatin1String(kColumns)));
    if (!query.exec())
        return records;

    while (query.next())
        records.append(readRow(query));

    return records;
}

bool CatalogIndex::markMissing(qint64 id, qint64 whenMs)
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return false;
    }

    // Only stamp the first time, so the dimmed card can say how long it's been
    // gone rather than resetting on every launcher open.
    QSqlQuery query = db.prepare(QStringLiteral(
        "UPDATE texture SET missing_since = ? WHERE id = ? AND missing_since IS NULL"));
    query.addBindValue(whenMs);
    query.addBindValue(id);
    if (!query.exec()) {
        db.setError(query.lastError().text());
        return false;
    }
    return true;
}

bool CatalogIndex::markPresent(qint64 id, qint64 fileSize, qint64 fileMtime)
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return false;
    }

    QSqlQuery query = db.prepare(QStringLiteral(
        "UPDATE texture SET missing_since = NULL, file_size = ?, file_mtime = ? WHERE id = ?"));
    query.addBindValue(fileSize);
    query.addBindValue(fileMtime);
    query.addBindValue(id);
    if (!query.exec()) {
        db.setError(query.lastError().text());
        return false;
    }
    return true;
}

qint64 CatalogIndex::relocate(qint64 id, const QString& newPath, qint64 fileSize,
                              qint64 fileMtime)
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return -1;
    }
    if (newPath.isEmpty())
        return -1;

    const TextureRecord moving = byId(id);
    if (!moving.isValid())
        return -1;

    Transaction tx(db);
    if (!tx.isActive())
        return -1;

    const TextureRecord existing = byPath(newPath);

    // Already indexed under the new path — usually because the user opened it
    // there before getting round to fixing the stale card. Fold the old row's
    // user data into it rather than failing on the UNIQUE constraint.
    if (existing.isValid() && existing.id != id) {
        QSqlQuery merge = db.prepare(QStringLiteral(
            "UPDATE texture SET "
            "  starred     = max(starred, ?), "
            "  created_at  = min(created_at, ?), "
            "  last_opened = max(coalesce(last_opened, 0), ?), "
            "  last_saved  = max(coalesce(last_saved, 0), ?), "
            "  missing_since = NULL "
            "WHERE id = ?"));
        merge.addBindValue(moving.starred ? 1 : 0);
        merge.addBindValue(moving.createdAt != 0 ? moving.createdAt : existing.createdAt);
        merge.addBindValue(moving.lastOpened);
        merge.addBindValue(moving.lastSaved);
        merge.addBindValue(existing.id);
        if (!merge.exec()) {
            db.setError(merge.lastError().text());
            return -1;
        }

        QSqlQuery moveTags = db.prepare(
            QStringLiteral("INSERT OR IGNORE INTO tag (texture_id, tag) "
                           "SELECT ?, tag FROM tag WHERE texture_id = ?"));
        moveTags.addBindValue(existing.id);
        moveTags.addBindValue(id);
        if (!moveTags.exec()) {
            db.setError(moveTags.lastError().text());
            return -1;
        }

        QSqlQuery drop = db.prepare(QStringLiteral("DELETE FROM texture WHERE id = ?"));
        drop.addBindValue(id);
        if (!drop.exec()) {
            db.setError(drop.lastError().text());
            return -1;
        }

        return tx.commit() ? existing.id : -1;
    }

    QSqlQuery query = db.prepare(QStringLiteral(
        "UPDATE texture SET path = ?, name = ?, file_size = ?, file_mtime = ?, "
        "missing_since = NULL WHERE id = ?"));
    query.addBindValue(newPath);
    query.addBindValue(QFileInfo(newPath).completeBaseName());
    query.addBindValue(fileSize);
    query.addBindValue(fileMtime);
    query.addBindValue(id);

    if (!query.exec()) {
        db.setError(query.lastError().text());
        return -1;
    }

    return tx.commit() ? id : -1;
}

// --- reads ----------------------------------------------------------------

QString CatalogIndex::whereClause(const Query& query)
{
    QStringList clauses;

    switch (query.filter) {
    case Filter::All:
        break;
    case Filter::Recents:
        // Matches the ix_recent partial index. Recents is "jump back in", so a
        // file that isn't there isn't useful; All and Starred still show it.
        clauses << QStringLiteral("last_opened IS NOT NULL")
                << QStringLiteral("missing_since IS NULL");
        break;
    case Filter::Starred:
        clauses << QStringLiteral("starred = 1");
        break;
    }

    if (!query.search.isEmpty()) {
        clauses << QStringLiteral(
            R"((name LIKE :search ESCAPE '\' OR EXISTS (
                   SELECT 1 FROM tag WHERE tag.texture_id = texture.id
                   AND tag.tag LIKE :search ESCAPE '\')))");
    }

    if (clauses.isEmpty())
        return QString();

    return QStringLiteral(" WHERE ") + clauses.join(QStringLiteral(" AND "));
}

QString CatalogIndex::orderByClause(const Query& query)
{
    const QString direction = query.ascending ? QStringLiteral("ASC") : QStringLiteral("DESC");

    switch (query.sort) {
    case SortKey::Name:
        return QStringLiteral(" ORDER BY name COLLATE NOCASE %1, id %1").arg(direction);
    case SortKey::Size:
        return QStringLiteral(" ORDER BY file_size %1, id %1").arg(direction);
    case SortKey::Opened:
        // Spelled out rather than using NULLS LAST so the ordering doesn't
        // depend on which SQLite version Qt happens to bundle. Never-opened
        // rows sort last either way.
        return QStringLiteral(" ORDER BY (last_opened IS NULL) ASC, last_opened %1, id %1")
            .arg(direction);
    case SortKey::Modified:
        break;
    }
    return QStringLiteral(" ORDER BY file_mtime %1, id %1").arg(direction);
}

QVector<TextureRecord> CatalogIndex::list(const Query& query) const
{
    QVector<TextureRecord> records;

    QString sql = QStringLiteral("SELECT %1 FROM texture").arg(QLatin1String(kColumns));
    sql += whereClause(query);
    sql += orderByClause(query);

    if (query.limit >= 0)
        sql += QStringLiteral(" LIMIT :limit OFFSET :offset");

    QSqlQuery q = const_cast<Database&>(db).prepare(sql);
    if (!query.search.isEmpty())
        q.bindValue(QStringLiteral(":search"),
                    QStringLiteral("%%%1%%").arg(escapeLike(query.search)));
    if (query.limit >= 0) {
        q.bindValue(QStringLiteral(":limit"), query.limit);
        q.bindValue(QStringLiteral(":offset"), query.offset);
    }

    if (!q.exec()) {
        const_cast<Database&>(db).setError(q.lastError().text());
        qWarning("catalog: list failed: %s", qPrintable(q.lastError().text()));
        return records;
    }

    while (q.next())
        records.append(readRow(q));

    return records;
}

int CatalogIndex::count(const Query& query) const
{
    QString sql = QStringLiteral("SELECT count(*) FROM texture");
    sql += whereClause(query);

    QSqlQuery q = const_cast<Database&>(db).prepare(sql);
    if (!query.search.isEmpty())
        q.bindValue(QStringLiteral(":search"),
                    QStringLiteral("%%%1%%").arg(escapeLike(query.search)));

    if (!q.exec() || !q.next())
        return 0;

    return q.value(0).toInt();
}

TextureRecord CatalogIndex::readRow(const QSqlQuery& query)
{
    TextureRecord rec;
    rec.id = query.value(0).toLongLong();
    rec.path = query.value(1).toString();
    rec.name = query.value(2).toString();
    rec.fileSize = query.value(3).toLongLong();
    rec.fileMtime = query.value(4).toLongLong();
    rec.width = query.value(5).toInt();
    rec.height = query.value(6).toInt();
    rec.nodeCount = query.value(7).toInt();
    rec.libVersion = query.value(8).toString();
    rec.channels = query.value(9).toInt();
    rec.createdAt = query.value(10).toLongLong();
    rec.lastOpened = query.value(11).isNull() ? 0 : query.value(11).toLongLong();
    rec.lastSaved = query.value(12).isNull() ? 0 : query.value(12).toLongLong();
    rec.starred = query.value(13).toBool();
    rec.missingSince = query.value(14).isNull() ? 0 : query.value(14).toLongLong();
    return rec;
}

TextureRecord CatalogIndex::byId(qint64 id) const
{
    QSqlQuery query = const_cast<Database&>(db).prepare(
        QStringLiteral("SELECT %1 FROM texture WHERE id = ?").arg(QLatin1String(kColumns)));
    query.addBindValue(id);

    if (!query.exec() || !query.next())
        return TextureRecord();

    return readRow(query);
}

TextureRecord CatalogIndex::byPath(const QString& path) const
{
    QSqlQuery query = const_cast<Database&>(db).prepare(
        QStringLiteral("SELECT %1 FROM texture WHERE path = ?").arg(QLatin1String(kColumns)));
    query.addBindValue(path);

    if (!query.exec() || !query.next())
        return TextureRecord();

    return readRow(query);
}

// --- tags -----------------------------------------------------------------

QStringList CatalogIndex::tags(qint64 id) const
{
    QStringList result;

    QSqlQuery query = const_cast<Database&>(db).prepare(
        QStringLiteral("SELECT tag FROM tag WHERE texture_id = ? ORDER BY tag"));
    query.addBindValue(id);

    if (!query.exec())
        return result;

    while (query.next())
        result << query.value(0).toString();

    return result;
}

bool CatalogIndex::addTag(qint64 id, const QString& tag)
{
    if (readOnly || tag.isEmpty()) {
        db.setError(QStringLiteral("index is read-only or tag is empty"));
        return false;
    }

    QSqlQuery query = db.prepare(
        QStringLiteral("INSERT OR IGNORE INTO tag (texture_id, tag) VALUES (?, ?)"));
    query.addBindValue(id);
    query.addBindValue(tag);
    if (!query.exec()) {
        db.setError(query.lastError().text());
        return false;
    }
    return true;
}

bool CatalogIndex::removeTag(qint64 id, const QString& tag)
{
    if (readOnly) {
        db.setError(QStringLiteral("index is read-only"));
        return false;
    }

    QSqlQuery query = db.prepare(
        QStringLiteral("DELETE FROM tag WHERE texture_id = ? AND tag = ?"));
    query.addBindValue(id);
    query.addBindValue(tag);
    if (!query.exec()) {
        db.setError(query.lastError().text());
        return false;
    }
    return query.numRowsAffected() > 0;
}

} // namespace catalog
