#include "catalogindex.h"

#include <QSqlQuery>
#include <QTemporaryDir>
#include <QtTest>

using namespace catalog;

namespace {

constexpr qint64 kT0 = 1'700'000'000'000LL; // arbitrary fixed "now", in ms

TextureRecord makeRecord(const QString& path)
{
    TextureRecord rec;
    rec.path = path;
    rec.name = QFileInfo(path).completeBaseName();
    rec.fileSize = 4096;
    rec.fileMtime = kT0;
    rec.width = 2048;
    rec.height = 2048;
    rec.nodeCount = 12;
    rec.libVersion = QStringLiteral("v3");
    rec.channels = ChannelAlbedo | ChannelNormal | ChannelRoughness;
    return rec;
}

} // namespace

class TestCatalogIndex : public QObject {
    Q_OBJECT

private slots:
    void init();
    void cleanup();

    void createsSchemaOnFirstOpen();
    void reopenPreservesRows();
    void refusesToWriteWhenSchemaIsNewer();

    void recordOpenedInsertsAndStamps();
    void recordOpenedTwiceDoesNotDuplicate();
    void createdAtSurvivesLaterWrites();
    void recordSavedStampsSavedNotOpened();
    void recordingClearsMissingFlag();
    void refusesRecordWithoutPath();

    void movedFileBecomesASeparateRow();

    void relocateRepointsAMissingRow();
    void relocateMergesWhenTargetIsAlreadyIndexed();
    void relocateRejectsUnknownRows();

    void markMissingStampsOnlyOnce();
    void markPresentUpdatesFileStateAndClearsMissing();

    void listFiltersRecentsExcludingMissing();
    void listFiltersStarredIncludingMissing();
    void listSortsAndPages();
    void searchMatchesNameAndTagsCaseInsensitively();
    void searchTreatsWildcardsLiterally();

    void tagsRoundTripAndCascadeOnDelete();
    void removeAllMissingOnlyRemovesMissing();

private:
    QString indexPath() const { return dir->filePath(QStringLiteral("index.db")); }

    QScopedPointer<QTemporaryDir> dir;
    QScopedPointer<CatalogIndex> index;
};

void TestCatalogIndex::init()
{
    dir.reset(new QTemporaryDir);
    QVERIFY(dir->isValid());
    index.reset(new CatalogIndex);
    QVERIFY(index->open(indexPath()));
}

void TestCatalogIndex::cleanup()
{
    index.reset();
    dir.reset();
}

void TestCatalogIndex::createsSchemaOnFirstOpen()
{
    QVERIFY(index->isOpen());
    QVERIFY(!index->isReadOnly());
    QCOMPARE(index->schemaVersion(), CatalogIndex::SchemaVersion);
    QCOMPARE(index->count(Query()), 0);
}

void TestCatalogIndex::reopenPreservesRows()
{
    TextureRecord rec = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordOpened(rec, kT0));

    index->close();
    QVERIFY(index->open(indexPath()));

    QCOMPARE(index->count(Query()), 1);
    const TextureRecord loaded = index->byPath(QStringLiteral("/tex/brick.texture"));
    QVERIFY(loaded.isValid());
    QCOMPARE(loaded.name, QStringLiteral("brick"));
    QCOMPARE(loaded.channels, int(ChannelAlbedo | ChannelNormal | ChannelRoughness));
    QCOMPARE(loaded.libVersion, QStringLiteral("v3"));
}

void TestCatalogIndex::refusesToWriteWhenSchemaIsNewer()
{
    // index.db cannot be regenerated by rescanning, so a file from a newer
    // build must be left strictly alone rather than migrated on a guess.
    TextureRecord rec = makeRecord(QStringLiteral("/tex/a.texture"));
    QVERIFY(index->recordOpened(rec, kT0));
    index->close();

    {
        Database raw;
        QVERIFY(raw.open(indexPath()));
        QVERIFY(raw.exec(QStringLiteral("UPDATE meta SET v = '999' WHERE k = 'schema_version'")));
    }

    QTest::ignoreMessage(QtWarningMsg,
                         QRegularExpression(QStringLiteral("newer than this build")));
    QVERIFY(index->open(indexPath()));
    QVERIFY(index->isReadOnly());

    // Reads still work — the launcher should show what it can.
    QCOMPARE(index->count(Query()), 1);

    TextureRecord blocked = makeRecord(QStringLiteral("/tex/b.texture"));
    QVERIFY(!index->recordOpened(blocked, kT0));
    QVERIFY(!index->setStarred(1, true));
    QVERIFY(!index->remove(1));
    QCOMPARE(index->count(Query()), 1);
}

void TestCatalogIndex::recordOpenedInsertsAndStamps()
{
    TextureRecord rec = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordOpened(rec, kT0));

    QVERIFY(rec.isValid());
    QCOMPARE(rec.lastOpened, kT0);
    QCOMPARE(rec.lastSaved, 0LL);
    QCOMPARE(rec.createdAt, kT0);
    QVERIFY(!rec.isMissing());
    QCOMPARE(index->count(Query()), 1);
}

void TestCatalogIndex::recordOpenedTwiceDoesNotDuplicate()
{
    TextureRecord first = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordOpened(first, kT0));

    TextureRecord second = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordOpened(second, kT0 + 5000));

    QCOMPARE(index->count(Query()), 1);
    QCOMPARE(second.id, first.id);
    QCOMPARE(second.lastOpened, kT0 + 5000);
}

void TestCatalogIndex::createdAtSurvivesLaterWrites()
{
    TextureRecord rec = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordOpened(rec, kT0));

    TextureRecord again = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordSaved(again, kT0 + 60'000));

    QCOMPARE(again.createdAt, kT0);
    QCOMPARE(again.lastOpened, kT0);          // preserved, not clobbered
    QCOMPARE(again.lastSaved, kT0 + 60'000);
}

void TestCatalogIndex::recordSavedStampsSavedNotOpened()
{
    TextureRecord rec = makeRecord(QStringLiteral("/tex/new.texture"));
    QVERIFY(index->recordSaved(rec, kT0));

    QCOMPARE(rec.lastSaved, kT0);
    QCOMPARE(rec.lastOpened, 0LL);

    // A never-opened row must not appear under Recents.
    Query recents;
    recents.filter = Filter::Recents;
    QCOMPARE(index->count(recents), 0);
}

void TestCatalogIndex::recordingClearsMissingFlag()
{
    TextureRecord rec = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordOpened(rec, kT0));
    QVERIFY(index->markMissing(rec.id, kT0 + 1000));
    QVERIFY(index->byId(rec.id).isMissing());

    TextureRecord again = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordOpened(again, kT0 + 2000));
    QVERIFY(!index->byId(rec.id).isMissing());
}

void TestCatalogIndex::refusesRecordWithoutPath()
{
    TextureRecord rec;
    QVERIFY(!index->recordOpened(rec, kT0));
    QCOMPARE(index->count(Query()), 0);
}

void TestCatalogIndex::movedFileBecomesASeparateRow()
{
    // Paths are identity. Recognizing that a file moved would need a content
    // hash or an mtime heuristic, and neither was worth its keep — so the old
    // row simply stays behind, flagged missing, and the user removes it. The
    // cost is losing stars and recency on a moved file; nothing breaks.
    TextureRecord original = makeRecord(QStringLiteral("/old/brick.texture"));
    QVERIFY(index->recordOpened(original, kT0));
    QVERIFY(index->setStarred(original.id, true));
    QVERIFY(index->addTag(original.id, QStringLiteral("stone")));
    QVERIFY(index->markMissing(original.id, kT0 + 1000));

    TextureRecord moved = makeRecord(QStringLiteral("/new/brick.texture"));
    QVERIFY(index->recordOpened(moved, kT0 + 2000));

    QCOMPARE(index->count(Query()), 2);
    QVERIFY(moved.id != original.id);

    // The old row is untouched and still dimmed, holding its own stars.
    const TextureRecord stale = index->byId(original.id);
    QVERIFY(stale.isValid());
    QVERIFY(stale.isMissing());
    QVERIFY(stale.starred);

    // The new one starts clean.
    QVERIFY(!moved.starred);
    QVERIFY(index->tags(moved.id).isEmpty());

    // And "Remove from Launcher" is the way out.
    QVERIFY(index->remove(original.id));
    QCOMPARE(index->count(Query()), 1);
}

void TestCatalogIndex::relocateRepointsAMissingRow()
{
    // The user-driven counterpart to not detecting moves: the launcher can't
    // guess where a file went, but Locate… lets the user say, and the row keeps
    // everything it had.
    TextureRecord rec = makeRecord(QStringLiteral("/old/brick.texture"));
    QVERIFY(index->recordOpened(rec, kT0));
    QVERIFY(index->setStarred(rec.id, true));
    QVERIFY(index->addTag(rec.id, QStringLiteral("stone")));
    QVERIFY(index->markMissing(rec.id, kT0 + 1000));

    const qint64 survivor =
        index->relocate(rec.id, QStringLiteral("/new/brick.texture"), 8192, kT0 + 5000);
    QCOMPARE(survivor, rec.id);

    const TextureRecord moved = index->byId(rec.id);
    QCOMPARE(moved.path, QStringLiteral("/new/brick.texture"));
    QCOMPARE(moved.name, QStringLiteral("brick"));
    QCOMPARE(moved.fileSize, 8192LL);
    QCOMPARE(moved.fileMtime, kT0 + 5000);
    QVERIFY(!moved.isMissing());
    QVERIFY(moved.starred);
    QCOMPARE(index->tags(moved.id), QStringList({QStringLiteral("stone")}));
    QCOMPARE(index->count(Query()), 1);
}

void TestCatalogIndex::relocateMergesWhenTargetIsAlreadyIndexed()
{
    // path is UNIQUE, so relocating onto a path that's already indexed has to
    // merge rather than fail — otherwise Locate… dead-ends exactly when the
    // user already opened the file at its new home.
    TextureRecord stale = makeRecord(QStringLiteral("/old/brick.texture"));
    QVERIFY(index->recordOpened(stale, kT0));
    QVERIFY(index->setStarred(stale.id, true));
    QVERIFY(index->addTag(stale.id, QStringLiteral("stone")));
    QVERIFY(index->markMissing(stale.id, kT0 + 1000));

    TextureRecord current = makeRecord(QStringLiteral("/new/brick.texture"));
    QVERIFY(index->recordOpened(current, kT0 + 2000));
    QVERIFY(!current.starred);

    const qint64 survivor =
        index->relocate(stale.id, QStringLiteral("/new/brick.texture"), 4096, kT0 + 2000);

    QCOMPARE(survivor, current.id);
    QVERIFY(!index->byId(stale.id).isValid());
    QCOMPARE(index->count(Query()), 1);

    const TextureRecord merged = index->byId(current.id);
    QVERIFY(merged.starred);                 // carried across
    QCOMPARE(merged.createdAt, kT0);         // earliest of the two
    QCOMPARE(index->tags(merged.id), QStringList({QStringLiteral("stone")}));
}

void TestCatalogIndex::relocateRejectsUnknownRows()
{
    QCOMPARE(index->relocate(999, QStringLiteral("/x.texture"), 1, 1), -1LL);
    QCOMPARE(index->relocate(1, QString(), 1, 1), -1LL);
}

void TestCatalogIndex::markMissingStampsOnlyOnce()
{
    TextureRecord rec = makeRecord(QStringLiteral("/tex/gone.texture"));
    QVERIFY(index->recordOpened(rec, kT0));

    QVERIFY(index->markMissing(rec.id, kT0 + 1000));
    QVERIFY(index->markMissing(rec.id, kT0 + 9999));

    // The card wants to say how long it's been gone, so the first sighting
    // wins rather than being reset on every launcher open.
    QCOMPARE(index->byId(rec.id).missingSince, kT0 + 1000);
}

void TestCatalogIndex::markPresentUpdatesFileStateAndClearsMissing()
{
    // What reconciliation does when a file turns out to still be there: record
    // the current size/mtime and un-dim the card. Comparing those two values
    // against the stored row is the system's only change detection — a caller
    // that sees them differ drops the cached thumbnail before calling this.
    TextureRecord rec = makeRecord(QStringLiteral("/tex/edited.texture"));
    QVERIFY(index->recordOpened(rec, kT0));
    QVERIFY(index->markMissing(rec.id, kT0 + 1000));

    QVERIFY(index->markPresent(rec.id, 8192, kT0 + 5000));

    const TextureRecord updated = index->byId(rec.id);
    QVERIFY(!updated.isMissing());
    QCOMPARE(updated.fileSize, 8192LL);
    QCOMPARE(updated.fileMtime, kT0 + 5000);
}

void TestCatalogIndex::listFiltersRecentsExcludingMissing()
{
    TextureRecord opened = makeRecord(QStringLiteral("/tex/opened.texture"));
    QVERIFY(index->recordOpened(opened, kT0));

    TextureRecord savedOnly = makeRecord(QStringLiteral("/tex/saved.texture"));
    QVERIFY(index->recordSaved(savedOnly, kT0));

    TextureRecord missing = makeRecord(QStringLiteral("/tex/missing.texture"));
    QVERIFY(index->recordOpened(missing, kT0));
    QVERIFY(index->markMissing(missing.id, kT0 + 1000));

    Query recents;
    recents.filter = Filter::Recents;
    const QVector<TextureRecord> rows = index->list(recents);

    QCOMPARE(rows.size(), 1);
    QCOMPARE(rows.first().path, QStringLiteral("/tex/opened.texture"));

    // All still shows everything, missing included — those cards render dimmed.
    QCOMPARE(index->count(Query()), 3);
}

void TestCatalogIndex::listFiltersStarredIncludingMissing()
{
    TextureRecord starred = makeRecord(QStringLiteral("/tex/star.texture"));
    QVERIFY(index->recordOpened(starred, kT0));
    QVERIFY(index->setStarred(starred.id, true));
    QVERIFY(index->markMissing(starred.id, kT0 + 1000));

    TextureRecord plain = makeRecord(QStringLiteral("/tex/plain.texture"));
    QVERIFY(index->recordOpened(plain, kT0));

    Query query;
    query.filter = Filter::Starred;
    const QVector<TextureRecord> rows = index->list(query);

    // An unmounted drive must not hide the things the user explicitly marked.
    QCOMPARE(rows.size(), 1);
    QCOMPARE(rows.first().path, QStringLiteral("/tex/star.texture"));
    QVERIFY(rows.first().isMissing());
}

void TestCatalogIndex::listSortsAndPages()
{
    const QStringList names = {QStringLiteral("charlie"), QStringLiteral("alpha"),
                               QStringLiteral("bravo"), QStringLiteral("delta")};
    for (int i = 0; i < names.size(); ++i) {
        TextureRecord rec = makeRecord(QStringLiteral("/tex/%1.texture").arg(names[i]));
        rec.fileMtime = kT0 + i * 1000;
        rec.fileSize = 1000 * (i + 1);
        QVERIFY(index->recordOpened(rec, kT0 + i * 1000));
    }

    Query byName;
    byName.sort = SortKey::Name;
    byName.ascending = true;
    QVector<TextureRecord> rows = index->list(byName);
    QCOMPARE(rows.size(), 4);
    QCOMPARE(rows[0].name, QStringLiteral("alpha"));
    QCOMPARE(rows[3].name, QStringLiteral("delta"));

    Query newestFirst;
    newestFirst.sort = SortKey::Modified;
    newestFirst.ascending = false;
    rows = index->list(newestFirst);
    QCOMPARE(rows.first().name, QStringLiteral("delta"));

    Query biggestFirst;
    biggestFirst.sort = SortKey::Size;
    biggestFirst.ascending = false;
    rows = index->list(biggestFirst);
    QCOMPARE(rows.first().fileSize, 4000LL);

    // Paging: the grid asks for a window, not the whole table.
    Query page;
    page.sort = SortKey::Name;
    page.ascending = true;
    page.limit = 2;
    page.offset = 1;
    rows = index->list(page);
    QCOMPARE(rows.size(), 2);
    QCOMPARE(rows[0].name, QStringLiteral("bravo"));
    QCOMPARE(rows[1].name, QStringLiteral("charlie"));

    // count() ignores paging — it's the total the scrollbar needs.
    QCOMPARE(index->count(page), 4);
}

void TestCatalogIndex::searchMatchesNameAndTagsCaseInsensitively()
{
    TextureRecord brick = makeRecord(QStringLiteral("/tex/BrickWall.texture"));
    QVERIFY(index->recordOpened(brick, kT0));

    TextureRecord metal = makeRecord(QStringLiteral("/tex/rust.texture"));
    QVERIFY(index->recordOpened(metal, kT0));
    QVERIFY(index->addTag(metal.id, QStringLiteral("Brickish")));

    TextureRecord other = makeRecord(QStringLiteral("/tex/cloth.texture"));
    QVERIFY(index->recordOpened(other, kT0));

    Query query;
    query.search = QStringLiteral("brick");
    const QVector<TextureRecord> rows = index->list(query);

    QCOMPARE(rows.size(), 2);
    QCOMPARE(index->count(query), 2);
}

void TestCatalogIndex::searchTreatsWildcardsLiterally()
{
    TextureRecord percent = makeRecord(QStringLiteral("/tex/50%25 grey.texture"));
    percent.name = QStringLiteral("50% grey");
    QVERIFY(index->recordOpened(percent, kT0));

    TextureRecord other = makeRecord(QStringLiteral("/tex/brick.texture"));
    QVERIFY(index->recordOpened(other, kT0));

    // Unescaped, "%" would match every row.
    Query query;
    query.search = QStringLiteral("%");
    QCOMPARE(index->count(query), 1);

    // Same for the single-character wildcard.
    query.search = QStringLiteral("_");
    QCOMPARE(index->count(query), 0);
}

void TestCatalogIndex::tagsRoundTripAndCascadeOnDelete()
{
    TextureRecord rec = makeRecord(QStringLiteral("/tex/tagged.texture"));
    QVERIFY(index->recordOpened(rec, kT0));

    QVERIFY(index->addTag(rec.id, QStringLiteral("stone")));
    QVERIFY(index->addTag(rec.id, QStringLiteral("outdoor")));
    QVERIFY(index->addTag(rec.id, QStringLiteral("stone"))); // idempotent

    QCOMPARE(index->tags(rec.id),
             QStringList({QStringLiteral("outdoor"), QStringLiteral("stone")}));

    QVERIFY(index->removeTag(rec.id, QStringLiteral("outdoor")));
    QCOMPARE(index->tags(rec.id), QStringList({QStringLiteral("stone")}));

    // The tag table is WITHOUT ROWID with an ON DELETE CASCADE foreign key;
    // this proves both are actually in force.
    QVERIFY(index->remove(rec.id));
    QCOMPARE(index->tags(rec.id), QStringList());
    QCOMPARE(index->database().scalar(QStringLiteral("SELECT count(*) FROM tag")), 0LL);
}

void TestCatalogIndex::removeAllMissingOnlyRemovesMissing()
{
    TextureRecord present = makeRecord(QStringLiteral("/tex/here.texture"));
    QVERIFY(index->recordOpened(present, kT0));

    TextureRecord gone = makeRecord(QStringLiteral("/tex/gone.texture"));
    QVERIFY(index->recordOpened(gone, kT0));
    QVERIFY(index->markMissing(gone.id, kT0 + 1000));

    QCOMPARE(index->removeAllMissing(), 1);
    QCOMPARE(index->count(Query()), 1);
    QVERIFY(index->byPath(QStringLiteral("/tex/here.texture")).isValid());
}

QTEST_GUILESS_MAIN(TestCatalogIndex)
#include "tst_catalogindex.moc"
